---
version: '3'
services:
  influxdb:
    image: influxdb@sha256:f02325b07c1105549c1e3099343f8cf8724497995b4795c5a1e0ddf5bd76fccf
    volumes:
      # Mount for influxdb data directory and configuration
      - /docker/docker-compose/influxdb/data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  # Use the influx cli to set up an influxdb instance. 
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - /docker/docker-compose/influxdb/influxdb2:/var/lib/influxdb2:rw
      - /docker/docker-compose/influxdb/ssl:/etc/ssl:rw
    environment: 
       # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - "DOCKER_INFLUXDB_INIT_USERNAME=${myusername}"
      - "DOCKER_INFLUXDB_INIT_PASSWORD=${passwordpasswordpassword}"
      - "DOCKER_INFLUXDB_INIT_ORG=${myorg}"
      - "DOCKER_INFLUXDB_INIT_BUCKET=${mybucket}"
      - "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${mytoken}"
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf@sha256:ae8d04a98fa87decb8eaedc776b64e2b638abf24f49c8df6e88b935454ffdedf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - /docker/docker-compose/influxdb/telegraf.conf:/etc/telegraf/telegraf.conf
    env_file:
      - .env
    environment: 
      - "DOCKER_INFLUXDB_INIT_ORG=${myorg}"
      - "DOCKER_INFLUXDB_INIT_BUCKET=${mybucket}"
      - "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${mytoken}"
    depends_on:
      - influxdb_cli
volumes:
  influxdb2:
